root = "/var/lib/k0s/containerd"
state = "/run/k0s/containerd"
version = 2

[grpc]
  address = "/run/k0s/containerd.sock"

[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = "registry.k8s.io/pause:3.8"
  max_concurrent_downloads = 3
  systemd_cgroup = false

  [plugins."io.containerd.grpc.v1.cri".containerd]
    snapshotter = "overlayfs"

  [plugins."io.containerd.grpc.v1.cri".registry]
    # Path to per-host registry configuration (hosts.toml files)
    config_path = "/etc/containerd/certs.d"
