apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: 10.77.67.100
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    files:
      - src: ./resources/etc/k0s/containerd/containerd.toml
        dst: /etc/k0s/containerd/containerd.toml
      - src: ./resources/etc/k0s/containerd/certs.d/192.168.59.11:5000/hosts.toml
        dst: /etc/k0s/containerd/certs.d/192.168.59.11:5000/hosts.toml

  - ssh:
      address: 10.77.67.144
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
    files:
      - src: ./resources/etc/k0s/containerd/containerd.toml
        dst: /etc/k0s/containerd/containerd.toml
      - src: ./resources/etc/k0s/containerd/certs.d/192.168.59.11:5000/hosts.toml
        dst: /etc/k0s/containerd/certs.d/192.168.59.11:5000/hosts.toml
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
