apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  k0s:
    version: v1.33.3+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          address: 192.168.59.10
          externalAddress: 192.168.59.10
          sans:
            - 192.168.59.10
        network:
          provider: calico
        storage:
          type: etcd
    
  hosts:
  - ssh:
      address: 192.168.59.10
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    hostname: control1
    privateAddress: 192.168.59.10

  - ssh:
      address: 192.168.59.21
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
    hostname: worker1
    privateAddress: 192.168.59.21

  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
